/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./resources/js/components/Api/Search.vue')['default']
    Table: typeof import('./resources/js/components/Home/Table.vue')['default']
    Translate: typeof import('./resources/js/components/Api/Translate.vue')['default']
  }
}
