version: "3.8"
services:
    # PHP
    php-fpm:
        networks:
            - general
        image: php:8.2-fpm-alpine
        build: ./docker/php-fpm
        container_name: php-fpm
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        tty: true
        stdin_open: true
    # NGINX
    nginx:
        networks:
            - general
        image: nginx:alpine
        container_name: webserver
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./storage/app/public:/var/www/html/public/storage
        ports:
            - "80:80"
        tty: true
        stdin_open: true
    # Mysql
    mysql:
        networks:
            - general
        platform: linux/x86_64
        image: mysql:8
        container_name: mysql
        working_dir: /var/www/html
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - .:/var/www/html
            - ./docker/mysql:/etc/mysql/conf.d
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        ports:
            - "3306:3306"
        tty: true
        stdin_open: true
    # Node
    node:
        networks:
            - general
        image: node:latest
        container_name: node
        working_dir: /var/www/html
        command: bash -c "npm install -g npm@latest && npm run build"
        volumes:
            - .:/var/www/html
        ports:
            - "3000:3000"
        tty: true
        stdin_open: true
volumes:
    mysqldata:
networks:
    general:
        name: general
        driver: bridge
